baseURL = "https://blog.daruyanagi.jp/"
languageCode = "ja-jp"
title = "blog.daruyanagi.jp"
theme = "daruyanagi"
publishDir = "docs"

googleAnalytics = "UA-53152247-5"

hasCJKLanguage = true

enableGitInfo = true

ignoreErrors = ["error-remote-getjson"]

[params]
  author = "daruyanagi"
  description = "いわゆる「だるろぐ」"
  github = "https://github.com/daruyanagi/blog.daruyanagi.jp/"
  og_image = "/no-image.png"
  logo_image = "/logo.png"

[services.rss]
  limit = 10

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions]
  linkify = false



  [privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false