baseURL = "https://blog.daruyanagi.jp/"
languageCode = "ja-jp"
title = "blog.daruyanagi.jp"
theme = "daruyanagi"
publishDir = "docs"

googleAnalytics = "UA-53152247-5"

hasCJKLanguage = true

enableGitInfo = true

[params]
  author = "daruyanagi"
  description = "いわゆる「だるろぐ」"
  github = "https://github.com/daruyanagi/blog.daruyanagi.jp/"
  og_image = "/no-image.png"

[services.rss]
  limit = 10

[markup.goldmark.renderer]
  unsafe = true
