baseURL = "https://blog.daruyanagi.jp/"
languageCode = "ja-jp"
title = "だるろぐ - だるやなぎのブログ"
theme = "daruyanagi"
publishDir = "docs"

googleAnalytics = "UA-53152247-5"

[markup.goldmark.renderer]
  unsafe = true
