baseURL = "https://blog.daruyanagi.jp/"
languageCode = "ja-jp"
title = "blog.daruyanagi.jp"
theme = "daruyanagi"
publishDir = "docs"

googleAnalytics = "UA-53152247-5"

[params]
  author = "daruyanagi"
  description = "いわゆる「だるろぐ」"

[markup.goldmark.renderer]
  unsafe = true
